; Specify the path to the pickle object storing the coordinates of the grid points
GRID_FILE = ../../../grids/Couette/Grid/grid_06_65_06.csv
SOLUTION_NAME = results

RESTART_SOLUTION = no
RESTART_SOLUTION_FILEPATH = Volume_CSV/results.csv

OUTPUT_FIELDS = secondary

; Specify the solver type
KIND_SOLVER = Euler



; Specify cartesian or axisymmetric. Cartesian by default
TOPOLOGY = 3D

; Fluid Properties
FLUID_GAMMA = 1.4
FLUID_NAME = Air
FLUID_MODEL = Ideal
FLUID_R_CONSTANT = 287.05       
FLUID_KINEMATIC_VISCOSITY = 1.57E-5
FLUID_CP = 1006            
FLUID_PRANDTL_NUMBER = 0.708
VISCOSITY_ACTIVE = yes

; Boundary condition file
BOUNDARY_CONDITIONS_FILEPATH = ../../../grids/Couette/Grid/grid_06_65_06_boundaries.csv

; Boundary Patches info
PER1 = periodic, 0, 0.00415, 0
PER2 = periodic, 1, 0.00415, 0
LOWER_WALL = no_slip_wall, 0, 0, 50, 0
UPPER_WALL = no_slip_wall, 0, 0, 0, 0
LATERAL_SIDE1 = inviscid_wall
LATERAL_SIDE2 = inviscid_wall

; Initialization parameters
INIT_MACH_NUMBER = 0.1                      
INIT_TEMPERATURE = 290                 
INIT_PRESSURE = 101300                      
INIT_DIRECTION = 0, 0, 1                          

; CFL number
CFL = 1.2
N_ITERATIONS = 100000
RESIDUALS_DROP_CONVERGENCE = 6


SAVE_UNSTEADY = no
SAVE_ITERATIONS_INTERVAL = 250

TIME_INTEGRATION_TYPE = 0

; Choose if local or global time-step method
TIME_STEP_METHOD = local

CONVECTION_SCHEME = JST

