[CFD]

; Specify the path to the pickle object storing the coordinates of the grid points
GRID_FILE = ../../grids/Schulz_Case_3/Grids/grid_400_400_onlyCoords.csv
SOLUTION_NAME = results

; Specify the kind of solver
KIND_SOLVER = Euler

RESTART_SOLUTION = yes
RESTART_SOLUTION_FILEPATH = ../../grids/Schulz_Case_3/Grids/grid_400_400_fullData.csv

TOPOLOGY = 2D

; Fluid Properties
FLUID_GAMMA = 1.4
FLUID_NAME = Air
FLUID_MODEL = Ideal
FLUID_R_CONSTANT = 287

; Boundary condition file
BOUNDARY_CONDITIONS_FILEPATH = ../../grids/Schulz_Case_3/Grids/grid_400x400_boundaries.csv

; Boundary Patches info
LEFT_PATCH = transparent
RIGHT_PATCH = transparent
UPPER_PATCH = transparent
LOWER_PATCH = transparent

; Initialization parameters
INIT_MACH_NUMBER = 0.7
INIT_TEMPERATURE = 285                   
INIT_PRESSURE = 101335                      
INIT_DIRECTION = 1, 0, 0     

; CFL number
CFL = 0.5
N_ITERATIONS = 850

SAVE_UNSTEADY = yes
SAVE_ITERATIONS_INTERVAL = 250

; Specify 0=RK41A (4-th order RK that favours boundary dissipation, CFL_MAX=2.58), 1=RK31B (3-rd order RK with good transient damping properties, CFL_MAX=1.53). 
TIME_INTEGRATION_TYPE = 0

; Choose if local or global time-step method
TIME_STEP_METHOD = fixed

FIXED_TIME_STEP = 0.0005

CONVECTION_SCHEME = Roe
MUSCL_RECONSTRUCTION = yes
FLUX_LIMITER = van leer


